# Autostart configuration for Hyprland

# Start the Waybar status bar
exec-once = waybar # Launch Waybar panel on startup

# Start the Hyprpaper wallpaper manager
exec-once = hyprpaper # Launch Hyprpaper utility on startup
