# Enable Inter-Process Communication (IPC) for dynamic wallpaper changes
ipc = on

# Preload the default wallpaper image into memory
preload = /home/qn37x/Projects/dotfiles/assets/wallpaper.jpg

# Set the preloaded wallpaper for all active monitors (wildcard syntax)
wallpaper = ,/home/qn37x/Projects/dotfiles/assets/wallpaper.jpg
