#!/usr/bin/env python3
"""
toggle_theme.py - Design Token Engine and Live Reload Manager for QN37x Dotfiles.
Switches active theme between light and dark according to DESIGN.md and triggers hot-reloads.
"""

from pathlib import Path
import os
import re
import subprocess
import sys
import shutil

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent

DESIGN_PATH = ROOT_DIR / "DESIGN.md"
ACTIVE_SYMLINK_PATH = ROOT_DIR / "themes/active"

def load_design():
    content = DESIGN_PATH.read_text()
    
    parts = content.split("---")
    if len(parts) < 3:
        raise ValueError("Could not parse YAML frontmatter in DESIGN.md")
        
    frontmatter = parts[1]
    
    theme_match = re.search(r"^theme:\s*(\w+)", frontmatter, re.MULTILINE)
    if not theme_match:
        raise ValueError("Could not find theme in DESIGN.md")
    theme = theme_match.group(1).strip()
    
    def parse_colors(section_name):
        colors = {}
        pattern = rf"^{section_name}:\s*\n((?:\s+[\w\-]+:\s*\"?[^\n\"]+\"?\n)+)"
        match = re.search(pattern, frontmatter, re.MULTILINE)
        if not match:
            raise ValueError(f"Could not parse section {section_name} in DESIGN.md")
        for line in match.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip()
                v = v.strip().strip('"\'')
                colors[k] = v
        return colors

    light_colors = parse_colors("light-colors")
    dark_colors = parse_colors("dark-colors")
    
    return content, theme, light_colors, dark_colors

def update_compiled_token_files(palette: dict[str, str], new_theme: str):
    # 1. Update theme waybar_colors.css
    theme_waybar_colors = ROOT_DIR / f"themes/{new_theme}/waybar_colors.css"
    lines = ["/* Generated by toggle_theme.py */"]
    for k, v in palette.items():
        css_var = f"@define-color {k} {v};"
        lines.append(css_var)
    if "ash" not in palette:
        lines.append("@define-color ash #444141;" if new_theme == "light" else "@define-color ash #b4b8b4;")
    if "charcoal" not in palette:
        lines.append("@define-color charcoal #171717;" if new_theme == "light" else "@define-color charcoal #dee2de;")
    lines.append(f"@define-color waybar-bg {'rgba(254, 255, 252, 0.94);' if new_theme == 'light' else 'rgba(23, 23, 23, 0.94);'}")
    theme_waybar_colors.write_text("\n".join(lines) + "\n")

    # 2. Update theme hypr_colors.lua
    theme_hypr_colors = ROOT_DIR / f"themes/{new_theme}/hypr_colors.lua"
    content = f"""return {{
    active_border_1 = "{palette.get('primary', '#41a1cf').lstrip('#')}",
    active_border_2 = "{palette.get('primary-dark', '#0081c0').lstrip('#')}",
    inactive_border = "{palette.get('border', '#dee2de').lstrip('#')}",
}}
"""
    theme_hypr_colors.write_text(content)

    # 3. Update Neovim background config
    nvim_bg = ROOT_DIR / "dot_config/nvim/lua/config/background.lua"
    nvim_bg.parent.mkdir(parents=True, exist_ok=True)
    nvim_bg.write_text(f'-- Auto-generated by toggle_theme.py\nvim.o.background = "{new_theme}"\n')

    # 5. Update GTK 3.0 and 4.0 configuration files for desktop apps
    home = Path.home()
    gtk_theme = "Adwaita-dark" if new_theme == "dark" else "Adwaita"
    dark_pref = "1" if new_theme == "dark" else "0"
    gtk_settings_content = f"""[Settings]
gtk-theme-name = {gtk_theme}
gtk-application-prefer-dark-theme = {dark_pref}
"""
    for gtk_ver in ("gtk-3.0", "gtk-4.0"):
        gtk_dir = home / f".config/{gtk_ver}"
        try:
            gtk_dir.mkdir(parents=True, exist_ok=True)
            (gtk_dir / "settings.ini").write_text(gtk_settings_content)
        except Exception:
            pass

def trigger_live_reloads(new_theme: str):
    # Helper to run command safely if binary exists in PATH
    def run_if_exists(cmd):
        if shutil.which(cmd[0]):
            try:
                subprocess.run(cmd, stderr=subprocess.DEVNULL, check=False)
            except Exception:
                pass

    # Update XDG desktop portal / GNOME interface scheme for Chrome, GTK, and web pages
    color_scheme = "prefer-dark" if new_theme == "dark" else "prefer-light"
    gtk_theme = "Adwaita-dark" if new_theme == "dark" else "Adwaita"
    run_if_exists(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", color_scheme])
    run_if_exists(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", gtk_theme])

    # Waybar reload signal or launch if not running
    try:
        waybar_running = subprocess.run(["pgrep", "-x", "waybar"], capture_output=True).returncode == 0
        if waybar_running:
            run_if_exists(["pkill", "-USR2", "waybar"])
        else:
            if shutil.which("waybar"):
                subprocess.Popen(["waybar"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass

    # SwayNC reload signals
    run_if_exists(["swaync-client", "-R"])
    run_if_exists(["swaync-client", "-rs"])
    # Hyprland reload
    run_if_exists(["hyprctl", "reload"])
    # Kitty terminal live theme reload (SIGUSR1 reloads kitty configuration without restarting)
    run_if_exists(["killall", "-SIGUSR1", "kitty"])

def main():
    design_content, current_theme, light_colors, dark_colors = load_design()
    
    if current_theme == "light":
        new_theme = "dark"
        new_palette = dark_colors
    else:
        new_theme = "light"
        new_palette = light_colors
        
    print(f"Switching theme from {current_theme} to {new_theme}...")
    
    # Update DESIGN.md theme and active colors block
    new_design_content = re.sub(
        rf"^theme:\s*{current_theme}",
        f"theme: {new_theme}",
        design_content,
        flags=re.MULTILINE
    )
    
    new_colors_block_lines = ["colors:"]
    for k, v in new_palette.items():
        new_colors_block_lines.append(f'  {k}: "{v}"')
    new_colors_block = "\n".join(new_colors_block_lines)
    
    pattern = r"^colors:\s*\n(?:\s+[\w\-]+:\s*\"?[^\n\"]+\"?\n?)+"
    new_design_content = re.sub(pattern, new_colors_block + "\n", new_design_content, flags=re.MULTILINE)
    
    DESIGN_PATH.write_text(new_design_content)
    print("[SUCCESS] Updated DESIGN.md active colors.")
    
    # Update active theme symlink
    if ACTIVE_SYMLINK_PATH.exists() or ACTIVE_SYMLINK_PATH.is_symlink():
        ACTIVE_SYMLINK_PATH.unlink()
    ACTIVE_SYMLINK_PATH.symlink_to(new_theme)
    print(f"[SUCCESS] Updated active theme symlink -> themes/{new_theme}")

    # Re-compile tokens and trigger hot-reload
    update_compiled_token_files(new_palette, new_theme)
    trigger_live_reloads(new_theme)
    print("[SUCCESS] Dynamic tokens recompiled and live reloads triggered.")

if __name__ == "__main__":
    main()
